### ISSUE TITLE
External backup 

### ISSUE THREAD

**Issue by sinnick** [klutchell/balena-bookstack#5]
Is there any way to backup the database and files externally? For example, connecting to the DB using something like DBeaver or some other SQL client? I've been running bookstack on a raspi-3 so far, but we need to move it to a more permanent device (a proper server), hence the need to extract the data

**Comment by klutchell** [comment]
For sure, I have the same requirements.

First off, the database is automatically dumped to a file at regular intervals, to avoid trying to backup an in-use-database.

https://github.com/klutchell/balena-bookstack/blob/8ffd833b0112af1d5e600971b44f0de4caa4936f/mariadb/Dockerfile#L3-L10

Secondly, to ensure the database is backed up offsite in a way that I can restore it in case of storage corruption, or in your case for migration, I would usually add a Duplicati service and backup the volumes as needed.

I've added an example to the readme here: https://github.com/klutchell/balena-bookstack/tree/main#extras

**Comment by bszafarz** [comment]
Hi @klutchell.
First of all thanks for your fork of bookstack project, adjusted to run quickly with balena.

If it's possible I'd need some more details about the backup handling. During "playing with bookstack" phase I've created a bunch of documents (books and sheets) which now have a value for me so I'm trying to be sure that some backup mechanism is implemented however I got some issue with that.

Firstly I've found in your Docker file - in fact it's also mentioned in above comment - that the backup is created once per an hour and saved on mariadb service under /var/lib/mysql directory. Using balena.cloud dashboard I've created an ssh session to mariadb container and found that file but I've struggled to get copy of it - container does not have scp nor curl bins hence I failed to move it to my local machine that way.

Secondly I've found your suggestion to use duplicati. I've managed to add it to the project (after verification on raw copy of bookstack that changing release will add missing container without purging content of exiting ones, just to be sure that my data are safe during that step). After adding duplicati service I've defined a scheduler to perform daily backup and store it on my OneDrive, as the source I've selected the /source/{bookstack,mariadb} directories and the backup is saved on cloud as expected.
However I've tried to restore books and config of bookstack from the backup to my raw copy of bookstack and despite duplicati's successful message (I've selected option to overwrite data during restore process) the raw bookstack does not contain all books and sheets from the original bookstack instance.

Did I you manage to verify that backup created by duplicati allows to recreate whole content to new (empty/raw) instance of bookstack?

Thanks in advance for your feedback!

**Comment by klutchell** [comment]
Did you verify via the timestamps that the backup database (and other files) were restored correctly via duplicati? It's likely that after restoring the files with duplicati you will want to re-import the database from the hourly mysql dump file as the existing database may have been in use during the original backup.

You can see how to restore mysql dump files here:
https://mariadb.com/kb/en/mysqldump/#restoring

Did duplicati give any errors or warnings during the restore?

**Comment by bszafarz** [comment]
Thanks to your message I've realize that the execution of `/var/lib/mysql # mysql -uroot -p$MYSQL_ROOT_PASSWORD < hourly-backup.sql ` after duplicati copy files to the new bookstack instance is essential... I tought that duplicati handle all for me and that's why I didn't see my book collection in first place. Now everything is just work as expected.
Thanks for your quick response!
